### ISSUE TITLE
Add comment to generated code

### ISSUE THREAD

**Issue by myshkin5** [nelsam/hel#20]
Hey Sam,

Could we get a comment added to the top of each generated file indicating the source of the generated code and some sort of warning about altering the code?

Hope all is well.

Thanks,
Dwayne

**Comment by nelsam** [comment]
Certainly.  I've always meant to do this, but got distracted by other projects.  I'll get that set up soon.

**Comment by nelsam** [comment]
Feel free to reopen (or make a pull request) if you want different wording, or if it's somehow not working for you.
