### ISSUE TITLE
Imports for packaged structs

### ISSUE THREAD

**Issue by jadekler** [nelsam/hel#26]
Vaguely speaking: when i have an interface whose return type is a struct that lives in the same package as the interface, `go generate` with `nelsam/hel` will create mock objects *without* importing the package and its struct. So, the mock object's return type will be not-found, instead of specifically imported (from the same package).

Example:

```go
package foo

type Bar struct {}
type Gaz interface {
  Whatever() []Bar
}
```

Will output something like:

```go
package foo_test

type mockGaz struct {
	WhateverCalled chan bool
        WhateverOutput struct {
		Ret0 chan []Bar
	}
}
```

When it should be:

```go
package foo_test 

import "foo"

type mockGaz struct {
	WhateverCalled chan bool
        WhateverOutput struct {
		Ret0 chan []foo.Bar
	}
}
```

**Comment by nelsam** [comment]
I discovered that the logic being used to prepend the package name to local types wasn't descending into some types that can have nested types.  It was already descending into functions, but not slices/arrays (they're the same thing in ast) or maps.  The most recent commit should fix that.

Please reopen if this isn't fixed.
