### ISSUE TITLE
Struct members have '_'

### ISSUE THREAD

**Issue by enocom** [nelsam/hel#31]
Struct fields are generated with an underscore to disambiguate from the receiver. This isn't necessary and fails to compile as the underscore is not included in field names when assigning to them in the mock implementations:

struct field definition:
```go
SendMsgInput  struct {
	M_ chan interface{}
}
```

struct field use:
```go
func (m *mockDopplerIngestor_PushServer) RecvMsg(m_ interface{}) error {
	m.RecvMsgCalled <- true
	m.RecvMsgInput.M <- m_
	return <-m.RecvMsgOutput.Ret0
}
```

/cc @jasonkeene

**Comment by nelsam** [comment]
This should be resolved.  If not, please reopen.

**Comment by apoydence** [comment]
This has a bug. The Channel definition also gets a `_` but it when the channel is written to it does not.

**Comment by nelsam** [comment]
@apoydence Can you provide a failing test?  [This test](https://github.com/nelsam/hel/blob/6c8e1fe5d599feed37d92ce745c3344a2a07f2e0/mocks/mocks_test.go#L563-L610) has me doubting you.  Are you sure you used the most recent version of hel?
