### ISSUE TITLE
Hel should have apoydence/eachers testhelpers package

### ISSUE THREAD

**Issue by poy** [nelsam/hel#34]
Eachers has a testhelpers package that is specific to hel's way of channels. I think the better home would be here.

**Comment by nelsam** [comment]
If you wouldn't mind throwing up a PR, I think it would make sense to have `github.com/nelsam/hel/helpers` or something.  I can't think of a better name, right now.

**Comment by apoydence** [comment]
Sounds reasonable. I'll make something happen, but I'll have to convert the tests from Ginkgo (pity...;)

**Comment by nelsam** [comment]
I've got `github.com/hel/pers` built out with some nice tools for hel mocks.  Closing as that should cover this.  Reopen if you think that doesn't solve the use case.
